### ISSUE TITLE
Correction proposal for SGW Shell File and docker-compose File

### ISSUE THREAD

**Issue by tofurukawa3** [ravens/docker-nextepc#4]
I set up docker-nextepc on Windows according to the Readme, but it seems that the following code needs to be modified.

`config/run_sgw.sh`

mkdir -p /usr/local/var/log/
-> mkdir -p /usr/local/var/log/open5gs

`provisioning/db/run_db.sh`
->In docker-compose-fauxrf.yml, it is defined in run.sh.
One of the following modifications is necessary.

* Modify YAML file (run.sh-> run_db.sh)
* Rename run_db.sh file under provisioning

**Comment by ravens** [comment]
Thanks ! the first one was on the radar but I did not spot the second one.
